{% set version = "1.1.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-redcaptidier
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/REDCapTidieR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/REDCapTidieR/REDCapTidieR_{{ version }}.tar.gz
  sha256: 9b3f809c9c84ca6cf939fbf98c3547108bc292f187eeed549bce3b695d15f828

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-redcapr >=1.1.0
    - r-checkmate
    - r-cli
    - r-dplyr
    - r-formattable
    - r-lobstr
    - r-lubridate
    - r-purrr
    - r-rlang
    - r-stringi
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tidyselect
  run:
    - r-base
    - r-redcapr >=1.1.0
    - r-checkmate
    - r-cli
    - r-dplyr
    - r-formattable
    - r-lobstr
    - r-lubridate
    - r-purrr
    - r-rlang
    - r-stringi
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tidyselect

test:
  commands:
    - $R -e "library('REDCapTidieR')"           # [not win]
    - "\"%R%\" -e \"library('REDCapTidieR')\""  # [win]

about:
  home: https://github.com/CHOP-CGTInformatics/REDCapTidieR, https://chop-cgtinformatics.github.io/REDCapTidieR/
  license: MIT
  summary: Convert 'REDCap' exports into tidy tables for easy handling of 'REDCap' repeat instruments and event arms.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
