{% set version = "0.3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-redcaptidier
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/REDCapTidieR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/REDCapTidieR/REDCapTidieR_{{ version }}.tar.gz
  sha256: dd9ddf7af9a00e2754c016370c6c4ed4d6b51c1de805ab7bb9ddccb4f489bb06

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-redcapr >=1.1.0
    - r-checkmate
    - r-cli
    - r-dplyr
    - r-formattable
    - r-lifecycle
    - r-lobstr
    - r-purrr
    - r-rlang
    - r-stringi
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tidyselect
  run:
    - r-base
    - r-redcapr >=1.1.0
    - r-checkmate
    - r-cli
    - r-dplyr
    - r-formattable
    - r-lifecycle
    - r-lobstr
    - r-purrr
    - r-rlang
    - r-stringi
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tidyselect

test:
  commands:
    - $R -e "library('REDCapTidieR')"           # [not win]
    - "\"%R%\" -e \"library('REDCapTidieR')\""  # [win]

about:
  home: https://github.com/CHOP-CGTInformatics/REDCapTidieR, https://chop-cgtinformatics.github.io/REDCapTidieR/
  license: MIT
  summary: Convert 'REDCap' exports into tidy tables for easy handling of 'REDCap' repeat instruments and event arms.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
